### PR TITLE
Add documentation for Test Driven Development

### LINKED ISSUE #2: Finishing up the python sythax-with TDD
Can we get someone who can write on Test Driven development.l am not so good in that area.After this we can move on to Web development.

### PR DESCRIPTION
**Pull request by rallytime**
Fixes #2 

@cachedout Please let me know if there is anything I can change or update here for this first swing. Thanks! :)

### CODE REVIEW

**Comment by cachedout** [comment]
@rallytime Thanks so much! You're awesome!

**Comment by ronnzw** [comment]
@rallytime thank you so much. @cachedout this looks ok to me.

**Comment by ZimboPy** [comment]
@rallytime thank you so much great work.You are awesome!!!

**Comment by rallytime** [comment]
Happy to do it! Thank you for the opportunity.

**Pull request merged**
